language: csharp
os: linux
dist: focal
mono: none
dotnet: 5.0.102
solution: FakeServer.sln
script:
  - dotnet restore
  - dotnet build
  - dotnet test FakeServer.Test/FakeServer.Test.csproj
env:
  - DOTNET_USE_POLLING_FILE_WATCHER=true